// <auto-generated />
using F1DriverApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1DriverApi.Migrations
{
    [DbContext(typeof(F1DriverApiContext))]
    [Migration("20230719210955_UpdatedSeasonData")]
    partial class UpdatedSeasonData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("F1DriverApi.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CareerPoints")
                        .HasColumnType("int");

                    b.Property<string>("CurrentTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DriverAge")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DriverNationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Podiums")
                        .HasColumnType("int");

                    b.Property<int>("RaceWins")
                        .HasColumnType("int");

                    b.Property<int>("WDCChampionships")
                        .HasColumnType("int");

                    b.Property<int>("currentSeasonPoints")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            CareerPoints = 2266,
                            CurrentTeam = "Red Bull Racing",
                            DriverAge = 25,
                            DriverName = "Max Verstappen",
                            DriverNationality = "Dutch",
                            Podiums = 87,
                            RaceWins = 43,
                            WDCChampionships = 2,
                            currentSeasonPoints = 255
                        },
                        new
                        {
                            DriverId = 2,
                            CareerPoints = 1357,
                            CurrentTeam = "Red Bull Racing",
                            DriverAge = 33,
                            DriverName = "Sergio Perez",
                            DriverNationality = "Mexican",
                            Podiums = 31,
                            RaceWins = 6,
                            WDCChampionships = 0,
                            currentSeasonPoints = 156
                        },
                        new
                        {
                            DriverId = 3,
                            CareerPoints = 2198,
                            CurrentTeam = "Aston Martin",
                            DriverAge = 41,
                            DriverName = "Fernando Alonso",
                            DriverNationality = "Spanish",
                            Podiums = 104,
                            RaceWins = 32,
                            WDCChampionships = 2,
                            currentSeasonPoints = 137
                        },
                        new
                        {
                            DriverId = 4,
                            CareerPoints = 4526,
                            CurrentTeam = "Mercedes-AMG Petronas F1 Team",
                            DriverAge = 38,
                            DriverName = "Lewis Hamilton",
                            DriverNationality = "British",
                            Podiums = 195,
                            RaceWins = 103,
                            WDCChampionships = 7,
                            currentSeasonPoints = 121
                        },
                        new
                        {
                            DriverId = 5,
                            CareerPoints = 376,
                            CurrentTeam = "Mercedes-AMG Petronas F1 Team",
                            DriverAge = 25,
                            DriverName = "George Russel",
                            DriverNationality = "British",
                            Podiums = 10,
                            RaceWins = 1,
                            WDCChampionships = 0,
                            currentSeasonPoints = 82
                        },
                        new
                        {
                            DriverId = 6,
                            CareerPoints = 865,
                            CurrentTeam = "Scuderia Ferrari",
                            DriverAge = 28,
                            DriverName = "Carlos Sainz Jr",
                            DriverNationality = "Spanish",
                            Podiums = 15,
                            RaceWins = 1,
                            WDCChampionships = 0,
                            currentSeasonPoints = 83
                        },
                        new
                        {
                            DriverId = 7,
                            CareerPoints = 940,
                            CurrentTeam = "Scuderia Ferrari",
                            DriverAge = 25,
                            DriverName = "Charles Leclerc",
                            DriverNationality = "Monegasque",
                            Podiums = 26,
                            RaceWins = 5,
                            WDCChampionships = 0,
                            currentSeasonPoints = 74
                        },
                        new
                        {
                            DriverId = 8,
                            CareerPoints = 238,
                            CurrentTeam = "Aston Martin",
                            DriverAge = 24,
                            DriverName = "Lance Stroll",
                            DriverNationality = "Canadian",
                            Podiums = 3,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 44
                        },
                        new
                        {
                            DriverId = 9,
                            CareerPoints = 395,
                            CurrentTeam = "Alpine",
                            DriverAge = 26,
                            DriverName = "Esteban Ocon",
                            DriverNationality = "French",
                            Podiums = 3,
                            RaceWins = 1,
                            WDCChampionships = 0,
                            currentSeasonPoints = 31
                        },
                        new
                        {
                            DriverId = 10,
                            CareerPoints = 348,
                            CurrentTeam = "Alpine",
                            DriverAge = 27,
                            DriverName = "Pierre Gasley",
                            DriverNationality = "French",
                            Podiums = 3,
                            RaceWins = 1,
                            WDCChampionships = 0,
                            currentSeasonPoints = 16
                        },
                        new
                        {
                            DriverId = 11,
                            CareerPoints = 470,
                            CurrentTeam = "McLaren F1 Team",
                            DriverAge = 23,
                            DriverName = "Lando Norris",
                            DriverNationality = "British",
                            Podiums = 7,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 42
                        },
                        new
                        {
                            DriverId = 12,
                            CareerPoints = 530,
                            CurrentTeam = "MoneyGram Haas F1 Team",
                            DriverAge = 35,
                            DriverName = "Niko Hulkenberg",
                            DriverNationality = "German",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 9
                        },
                        new
                        {
                            DriverId = 13,
                            CareerPoints = 5,
                            CurrentTeam = "McLaren F1 Team",
                            DriverAge = 22,
                            DriverName = "Oscar Piastri",
                            DriverNationality = "Australian",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 17
                        },
                        new
                        {
                            DriverId = 14,
                            CareerPoints = 1792,
                            CurrentTeam = "Alfa Romeo F1 Team",
                            DriverAge = 33,
                            DriverName = "Valtteri Bottas",
                            DriverNationality = "Finnish",
                            Podiums = 67,
                            RaceWins = 10,
                            WDCChampionships = 0,
                            currentSeasonPoints = 5
                        },
                        new
                        {
                            DriverId = 15,
                            CareerPoints = 10,
                            CurrentTeam = "Alfa Romeo F1 Team",
                            DriverAge = 24,
                            DriverName = "Zho Guanyu",
                            DriverNationality = "Chinese",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 4
                        },
                        new
                        {
                            DriverId = 16,
                            CareerPoints = 46,
                            CurrentTeam = "Scuderia AlphaTauri",
                            DriverAge = 23,
                            DriverName = "Yuki Tsunoda",
                            DriverNationality = "Japanese",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 2
                        },
                        new
                        {
                            DriverId = 17,
                            CareerPoints = 185,
                            CurrentTeam = "MoneyGram Haas F1 Team",
                            DriverAge = 30,
                            DriverName = "Kevin Magnussen",
                            DriverNationality = "Danish",
                            Podiums = 1,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 2
                        },
                        new
                        {
                            DriverId = 18,
                            CareerPoints = 212,
                            CurrentTeam = "Williams Racing",
                            DriverAge = 27,
                            DriverName = "Alex Albon",
                            DriverNationality = "Thai",
                            Podiums = 2,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 11
                        },
                        new
                        {
                            DriverId = 19,
                            CareerPoints = 2,
                            CurrentTeam = "None",
                            DriverAge = 28,
                            DriverName = "Nyck de Vries",
                            DriverNationality = "Dutch",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 0
                        },
                        new
                        {
                            DriverId = 20,
                            CareerPoints = 0,
                            CurrentTeam = "Williams Racing",
                            DriverAge = 22,
                            DriverName = "Logan Sargeant",
                            DriverNationality = "American",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0,
                            currentSeasonPoints = 0
                        },
                        new
                        {
                            DriverId = 21,
                            CareerPoints = 1311,
                            CurrentTeam = "Scuderia AlphaTauri",
                            DriverAge = 34,
                            DriverName = "Daniel Riccardio",
                            DriverNationality = "Australian",
                            Podiums = 32,
                            RaceWins = 8,
                            WDCChampionships = 0,
                            currentSeasonPoints = 0
                        });
                });

            modelBuilder.Entity("F1DriverApi.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TeamBase")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamChampionships")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeamNationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeamPrincipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            TeamBase = "Milton Keynes, United Kingdom",
                            TeamChampionships = 5,
                            TeamName = "Red Bull Racing",
                            TeamNationality = "Austrian",
                            TeamPrincipal = "Christian Horner"
                        },
                        new
                        {
                            TeamId = 2,
                            TeamBase = "Silverstone, United Kingdom",
                            TeamChampionships = 0,
                            TeamName = "Aston Martin",
                            TeamNationality = "British",
                            TeamPrincipal = "Mike Krack"
                        },
                        new
                        {
                            TeamId = 3,
                            TeamBase = "Brackley, United Kingdom",
                            TeamChampionships = 9,
                            TeamName = "Mercedes-AMG Petronas F1 Team",
                            TeamNationality = "German",
                            TeamPrincipal = "Toto Wolff"
                        },
                        new
                        {
                            TeamId = 4,
                            TeamBase = "Maranello, Italy",
                            TeamChampionships = 16,
                            TeamName = "Scuderia Ferrari",
                            TeamNationality = "Italian",
                            TeamPrincipal = "Frederic Vasseur"
                        },
                        new
                        {
                            TeamId = 5,
                            TeamBase = "Enstone, United Kingdom",
                            TeamChampionships = 0,
                            TeamName = "Alpine",
                            TeamNationality = "French",
                            TeamPrincipal = "Otmar Szafnauer"
                        },
                        new
                        {
                            TeamId = 6,
                            TeamBase = "Woking, United Kingdom",
                            TeamChampionships = 8,
                            TeamName = "McLaren F1 Team",
                            TeamNationality = "British",
                            TeamPrincipal = "Andrea Stella"
                        },
                        new
                        {
                            TeamId = 7,
                            TeamBase = "Kannapolis, United States",
                            TeamChampionships = 0,
                            TeamName = "MoneyGram Haas F1 Team",
                            TeamNationality = "American",
                            TeamPrincipal = "Guenther Steiner"
                        },
                        new
                        {
                            TeamId = 8,
                            TeamBase = "Hinwil, Switzerland",
                            TeamChampionships = 0,
                            TeamName = "Alfa Romeo F1 Team",
                            TeamNationality = "Swiss",
                            TeamPrincipal = "Alessandro Alunni Bravi"
                        },
                        new
                        {
                            TeamId = 9,
                            TeamBase = "Faenza, Italy",
                            TeamChampionships = 0,
                            TeamName = "Scuderia AlphaTauri",
                            TeamNationality = "Italian",
                            TeamPrincipal = "Franz Tost"
                        },
                        new
                        {
                            TeamId = 10,
                            TeamBase = "Grove, United Kingdom",
                            TeamChampionships = 9,
                            TeamName = "Williams Racing",
                            TeamNationality = "British",
                            TeamPrincipal = "James Vowles"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
