// <auto-generated />
using F1DriverApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1DriverApi.Migrations
{
    [DbContext(typeof(F1DriverApiContext))]
    partial class F1DriverApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("F1DriverApi.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CareerPoints")
                        .HasColumnType("int");

                    b.Property<string>("CurrentTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DriverAge")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DriverNationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Podiums")
                        .HasColumnType("int");

                    b.Property<int>("RaceWins")
                        .HasColumnType("int");

                    b.Property<int>("WDCChampionships")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            CareerPoints = 2181,
                            CurrentTeam = "Red Bull Racing",
                            DriverAge = 25,
                            DriverName = "Max Verstappen",
                            DriverNationality = "Dutch",
                            Podiums = 84,
                            RaceWins = 40,
                            WDCChampionships = 2
                        },
                        new
                        {
                            DriverId = 2,
                            CareerPoints = 1318,
                            CurrentTeam = "Red Bull Racing",
                            DriverAge = 33,
                            DriverName = "Sergio Perez",
                            DriverNationality = "Mexican",
                            Podiums = 30,
                            RaceWins = 6,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 3,
                            CareerPoints = 2160,
                            CurrentTeam = "Aston Martin",
                            DriverAge = 41,
                            DriverName = "Fernando Alonso",
                            DriverNationality = "Spanish",
                            Podiums = 103,
                            RaceWins = 32,
                            WDCChampionships = 2
                        },
                        new
                        {
                            DriverId = 4,
                            CareerPoints = 4492,
                            CurrentTeam = "Mercedes-AMG Petronas F1 Team",
                            DriverAge = 38,
                            DriverName = "Lewis Hamilton",
                            DriverNationality = "British",
                            Podiums = 193,
                            RaceWins = 103,
                            WDCChampionships = 7
                        },
                        new
                        {
                            DriverId = 5,
                            CareerPoints = 359,
                            CurrentTeam = "Mercedes-AMG Petronas F1 Team",
                            DriverAge = 25,
                            DriverName = "George Russel",
                            DriverNationality = "British",
                            Podiums = 10,
                            RaceWins = 1,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 6,
                            CareerPoints = 840,
                            CurrentTeam = "Scuderia Ferrari",
                            DriverAge = 28,
                            DriverName = "Carlos Sainz Jr",
                            DriverNationality = "Spanish",
                            Podiums = 15,
                            RaceWins = 1,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 7,
                            CareerPoints = 910,
                            CurrentTeam = "Scuderia Ferrari",
                            DriverAge = 25,
                            DriverName = "Charles Leclerc",
                            DriverNationality = "Monegasque",
                            Podiums = 25,
                            RaceWins = 5,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 8,
                            CareerPoints = 229,
                            CurrentTeam = "Aston Martin",
                            DriverAge = 24,
                            DriverName = "Lance Stroll",
                            DriverNationality = "Canadian",
                            Podiums = 3,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 9,
                            CareerPoints = 389,
                            CurrentTeam = "Alpine",
                            DriverAge = 26,
                            DriverName = "Esteban Ocon",
                            DriverNationality = "French",
                            Podiums = 3,
                            RaceWins = 1,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 10,
                            CareerPoints = 347,
                            CurrentTeam = "Alpine",
                            DriverAge = 27,
                            DriverName = "Pierre Gasley",
                            DriverNationality = "French",
                            Podiums = 3,
                            RaceWins = 1,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 11,
                            CareerPoints = 440,
                            CurrentTeam = "McLaren F1 Team",
                            DriverAge = 23,
                            DriverName = "Lando Norris",
                            DriverNationality = "British",
                            Podiums = 6,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 12,
                            CareerPoints = 527,
                            CurrentTeam = "MoneyGram Haas F1 Team",
                            DriverAge = 35,
                            DriverName = "Niko Hulkenberg",
                            DriverNationality = "German",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 13,
                            CareerPoints = 5,
                            CurrentTeam = "McLaren F1 Team",
                            DriverAge = 22,
                            DriverName = "Oscar Piastri",
                            DriverNationality = "Australian",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 14,
                            CareerPoints = 1791,
                            CurrentTeam = "Alfa Romeo F1 Team",
                            DriverAge = 33,
                            DriverName = "Valtteri Bottas",
                            DriverNationality = "Finnish",
                            Podiums = 67,
                            RaceWins = 10,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 15,
                            CareerPoints = 10,
                            CurrentTeam = "Alfa Romeo F1 Team",
                            DriverAge = 24,
                            DriverName = "Zho Guanyu",
                            DriverNationality = "Chinese",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 16,
                            CareerPoints = 46,
                            CurrentTeam = "Scuderia AlphaTauri",
                            DriverAge = 23,
                            DriverName = "Yuki Tsunoda",
                            DriverNationality = "Japanese",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 17,
                            CareerPoints = 185,
                            CurrentTeam = "MoneyGram Haas F1 Team",
                            DriverAge = 30,
                            DriverName = "Kevin Magnussen",
                            DriverNationality = "Danish",
                            Podiums = 1,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 18,
                            CareerPoints = 202,
                            CurrentTeam = "Williams Racing",
                            DriverAge = 27,
                            DriverName = "Alex Albon",
                            DriverNationality = "Thai",
                            Podiums = 2,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 19,
                            CareerPoints = 2,
                            CurrentTeam = "Scuderia AlphaTauri",
                            DriverAge = 28,
                            DriverName = "Nyck de Vries",
                            DriverNationality = "Dutch",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0
                        },
                        new
                        {
                            DriverId = 20,
                            CareerPoints = 0,
                            CurrentTeam = "Williams Racing",
                            DriverAge = 22,
                            DriverName = "Logan Sargeant",
                            DriverNationality = "American",
                            Podiums = 0,
                            RaceWins = 0,
                            WDCChampionships = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
